USE lab;

CREATE TABLE CUSTOMERS
(
    ID INT,
    NAME VARCHAR(50),
    AGE INT,
    ADDRESS VARCHAR(50),
    SALARY DECIMAL(10,2)
);

-- 1. Create a tiny log table first
CREATE TABLE IF NOT EXISTS TRIGGER_LOGS (
    Log_Message VARCHAR(255)
);

-- 2. Modify your trigger to INSERT instead of SELECT

CREATE TRIGGER Insert_log
AFTER INSERT ON CUSTOMERS
FOR EACH ROW
BEGIN
    INSERT INTO TRIGGER_LOGS 
    VALUES (CONCAT('INSERTION HAPPENED : ', NEW.SALARY));
END 

INSERT INTO CUSTOMERS (ID, NAME, AGE, ADDRESS, SALARY) 
VALUES (99, 'Test User', 25, 'Bangalore', 75000.00);

SELECT * FROM TRIGGER_LOGS;