-- 14.
-- Consider the following schema and write the SQL queries:

-- EMP (SSN, NAME, ADDR, SALARY, SEX, DNO)
-- DEP (DNO, DNAME, MGRSSN)
-- DEP_LOCN (DNO, DLOCN)
-- WORKSON (SSN, PNO, NOHRS)
-- DEPENDENT (SSN, DEPNTNAME, DEPNTSEX, DEPNTRELATIONSHIP)



USE lab;

CREATE TABLE EMP(
    SSN INT PRIMARY KEY,
    E_name VARCHAR(50),
    ADDR VARCHAR(50),
    SALARY INT,
    SEX VARCHAR(1),
    DNO INT
);
CREATE TABLE DEP(
    DNO INT PRIMARY KEY,
    DNAME VARCHAR(50),
    MGRSSN INT
);

ALTER TABLE EMP
ADD Foreign Key (DNO) REFERENCES DEP(DNO);

CREATE TABLE DEP_LOCN (
    DNO INT, 
    DLOCN VARCHAR(50));

ALTER TABLE DEP_LOCN
ADD FOREIGN KEY (DNO) REFERENCES DEP(DNO);

CREATE TABLE WORKSON (
    DNO INT,
    PNO INT, 
    NOHRS INT,
    FOREIGN KEY(DNO) REFERENCES DEP(DNO));

CREATE TABLE DEPENDENT(
    SSN INT,
    DEPNTNAME VARCHAR(30),
    SEPNTSEX VARCHAR(1),
    DEPNTRELATIONSHIP VARCHAR(30)  
);
-- EMP (SSN, NAME, ADDR, SALARY, SEX, DNO)


-- DEP (DNO, DNAME, MGRSSN)
INSERT INTO DEP VALUES(5,"Geetha",123);
INSERT INTO DEP VALUES(4,"Pooja",124);

INSERT INTO EMP VALUES(106,'ABC','Bangalore',39000,'F',5);

INSERT INTO EMP VALUES(101,"XYZ","Chennai",95000,"F",4);

INSERT INTO EMP VALUES(107,'Vce','Delhi',32000,'M',5);

-- WORKSON (dno, PNO, NOHRS)
INSERT INTO WORKSON VALUES(5,1234567890,5);

-- DEPENDENT (SSN, DEPNTNAME, DEPNTSEX, DEPNTRELATIONSHIP)
INSERT INTO DEPENDENT VALUES(100,"Finance","F","Daughter");

-- Retrieve all employees in department 5 whose salary is between $30,000 and $40,000.
SELECT E.*
FROM EMP E
JOIN DEP D
ON E.DNO = D.DNO
WHERE E.DNO=5
AND SALARY BETWEEN 30000 AND 40000;


-- Retrieve the names of employees whose salary is greater than the salary of all the employees in department 5.

SELECT E_name,SALARY
FROM EMP
WHERE SALARY > ALL (
    SELECT SALARY
    FROM EMP 
    WHERE DNO=5
);
