CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE Employee(
    EMPNO INT,
    ENAME VARCHAR(50),
    JOB VARCHAR(30),
    MANAGER_NO INT,
    SAL FLOAT,
    COMMISSION FLOAT
);

START TRANSACTION;
INSERT INTO Employee VALUES(101,"Abc","CEO",201,10000.00,150.00);
INSERT INTO Employee VALUES(102,"xYz","Manager",202,1000.00,10.00);
SELECT * FROM Employee;

ROLLBACK;
ALTER TABLE Employee
ADD PRIMARY KEY(MANAGER_NO);
ALTER TABLE Employee
MODIFY ENAME VARCHAR(50) NOT NULL;

INSERT INTO Employee VALUES(107,NULL,'Lead',1300,145.00,90.00);

DROP TABLE Employee;
